In [1]:
print("hello")

hello

In [5]:
import pandas as pd
df=pd.read_csv(r"C:\Users\khushbu\Desktop\123..csv")
print(df)

     Name     Khushbu
0     Age          20
1    City    Palampur
2  Flower  White Rose
3    cake   chocolate

In [7]:
import pandas as pd
data={"name":['Khushbu','Komal','Prachi','Anshika'],
      "cource":['ece','civil','cse','electrical']}
df=pd.DataFrame(data)
print(df)

      name      cource
0  Khushbu         ece
1    Komal       civil
2   Prachi         cse
3  Anshika  electrical

In [9]:
df.head(1)

      name cource
0  Khushbu    ece

In [11]:
df.head()  #select data from top to bottam

      name      cource
0  Khushbu         ece
1    Komal       civil
2   Prachi         cse
3  Anshika  electrical

In [13]:
df.tail(1)  #select data from bottam to top

      name      cource
3  Anshika  electrical

In [15]:
df.tail()

      name      cource
0  Khushbu         ece
1    Komal       civil
2   Prachi         cse
3  Anshika  electrical

In [17]:
df.info()  #for get information

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   cource  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [19]:
df.describe()

           name cource
count         4      4
unique        4      4
top     Khushbu    ece
freq          1      1

In [21]:
df.shape

(4, 2)

In [23]:
df.columns

Index(['name', 'cource'], dtype='str')

In [26]:
df['roll no']=[1,2,3,4]
print(df)

      name      cource  roll  roll no
0  Khushbu         ece     1        1
1    Komal       civil     2        2
2   Prachi         cse     3        3
3  Anshika  electrical     4        4

In [29]:
df.insert(1,'age',[100,90,80,70])
print(df)

      name  age  marks      cource  roll  roll no
0  Khushbu  100    100         ece     1        1
1    Komal   90     90       civil     2        2
2   Prachi   80     80         cse     3        3
3  Anshika   70     70  electrical     4        4

In [32]:
df.drop(index=[2],inplace=True)
print(df)

      name  age  marks      cource  roll  roll no
1    Komal   90     90       civil     2        2
3  Anshika   70     70  electrical     4        4

In [34]:
data={"name":['Khushbu','Komal','Prachi','Anshika',None],
      "cource":['ece','civil','cse','electrical',None]}
df1=pd.DataFrame(data)
print(df1)

      name      cource
0  Khushbu         ece
1    Komal       civil
2   Prachi         cse
3  Anshika  electrical
4      NaN         NaN

In [36]:
data={"name":['Khushbu','Komal','Prachi','Anshika'],
      "cource":['ece','civil','cse','electrical'],
      "salary":[1000,2000,3000,4000]}
df2=pd.DataFrame(data)
print(df2)

      name      cource  salary
0  Khushbu         ece    1000
1    Komal       civil    2000
2   Prachi         cse    3000
3  Anshika  electrical    4000

In [38]:
df2.isnull()

    name  cource  salary
0  False   False   False
1  False   False   False
2  False   False   False
3  False   False   False

In [41]:
df2.fillna(0,inplace=True)

      name      cource  salary
0  Khushbu         ece    1000
1    Komal       civil    2000
2   Prachi         cse    3000
3  Anshika  electrical    4000

In [1]:
print(df2.groupby('cource')['salary'].mean())

NameError: name 'df2' is not defined