In [3]:
import pandas as pd
data = {
    'Product_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Product_Name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones', 'Printer', 'Tablet', 'Camera', 'Smartphone', 'Speaker'],
    'Category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 'Accessories', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Accessories'],
    'Price': [70000, 1200, 2500, 15000, 2000, 10000, 25000, 30000, 40000, 3500],
    'Quantity': [5, 50, 40, 10, 35, 7, 15, 8, 12, 25],
    'Discount(%)': [10, 5, 5, 8, 10, 15, 7, 10, 12, 5]
}
df_1=pd.DataFrame(data)
print(df_1)

   Product_ID Product_Name     Category  Price  Quantity  Discount(%)
0         101       Laptop  Electronics  70000         5           10
1         102        Mouse  Accessories   1200        50            5
2         103     Keyboard  Accessories   2500        40            5
3         104      Monitor  Electronics  15000        10            8
4         105   Headphones  Accessories   2000        35           10
5         106      Printer  Electronics  10000         7           15
6         107       Tablet  Electronics  25000        15            7
7         108       Camera  Electronics  30000         8           10
8         109   Smartphone  Electronics  40000        12           12
9         110      Speaker  Accessories   3500        25            5

In [5]:
df_1['product number']=[1,2,3,4,5,6,7,8,9,10]
print(df_1)

   Product_ID Product_Name     Category  Price  Quantity  Discount(%)  \
0         101       Laptop  Electronics  70000         5           10
1         102        Mouse  Accessories   1200        50            5
2         103     Keyboard  Accessories   2500        40            5
3         104      Monitor  Electronics  15000        10            8
4         105   Headphones  Accessories   2000        35           10
5         106      Printer  Electronics  10000         7           15
6         107       Tablet  Electronics  25000        15            7
7         108       Camera  Electronics  30000         8           10
8         109   Smartphone  Electronics  40000        12           12
9         110      Speaker  Accessories   3500        25            5

   product number
0               1
1               2
2               3
3               4
4               5
5               6
6               7
7               8
8               9
9              10

In [7]:
df_1['revenue']=df_1['Price']*df_1['Quantity'] *(1- df_1['Discount(%)']/100)
df_1.head()

,Product_ID,Product_Name,Category,Price,Quantity,Discount(%),product number,revenue
0,101,Laptop,Electronics,70000,5,10,1,315000.0
1,102,Mouse,Accessories,1200,50,5,2,57000.0
2,103,Keyboard,Accessories,2500,40,5,3,95000.0
3,104,Monitor,Electronics,15000,10,8,4,138000.0
4,105,Headphones,Accessories,2000,35,10,5,63000.0

In [9]:
# do laptop exist in our data set
print(df_1['Product_Name']=='Laptop')

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Product_Name, dtype: bool

In [11]:
# where do the laptop exist
print(df_1.index[df_1['Product_Name']=='Laptop'].tolist())

[0]

In [13]:
# to check the unique elements from list
print(df_1['Product_Name'].unique())

<StringArray>
[    'Laptop',      'Mouse',   'Keyboard',    'Monitor', 'Headphones',
    'Printer',     'Tablet',     'Camera', 'Smartphone',    'Speaker']
Length: 10, dtype: str

In [15]:
# to check the quantity of unique elements
print(df_1['Product_Name'].nunique())

10

In [17]:
# to get specific data from the data set
df_1[["Product_Name","Category","Price"]].head()

  Product_Name     Category  Price
0       Laptop  Electronics  70000
1        Mouse  Accessories   1200
2     Keyboard  Accessories   2500
3      Monitor  Electronics  15000
4   Headphones  Accessories   2000

In [19]:
df_1.head()

,Product_ID,Product_Name,Category,Price,Quantity,Discount(%),product number,revenue
0,101,Laptop,Electronics,70000,5,10,1,315000.0
1,102,Mouse,Accessories,1200,50,5,2,57000.0
2,103,Keyboard,Accessories,2500,40,5,3,95000.0
3,104,Monitor,Electronics,15000,10,8,4,138000.0
4,105,Headphones,Accessories,2000,35,10,5,63000.0

In [21]:
# filtering the data
print(df_1[df_1['revenue']>200000])

   Product_ID Product_Name     Category  Price  Quantity  Discount(%)  \
0         101       Laptop  Electronics  70000         5           10
6         107       Tablet  Electronics  25000        15            7
7         108       Camera  Electronics  30000         8           10
8         109   Smartphone  Electronics  40000        12           12

   product number   revenue
0               1  315000.0
6               7  348750.0
7               8  216000.0
8               9  422400.0

In [23]:
# if you want the shorted data
df_1[df_1['revenue']>200000].sort_values(by='revenue',ascending=False).head(3)

,Product_ID,Product_Name,Category,Price,Quantity,Discount(%),product number,revenue
8,109,Smartphone,Electronics,40000,12,12,9,422400.0
6,107,Tablet,Electronics,25000,15,7,7,348750.0
0,101,Laptop,Electronics,70000,5,10,1,315000.0

In [25]:
print(df_1[df_1['revenue']>200000].sort_values(by='revenue',ascending=True).head(3))

   Product_ID Product_Name     Category  Price  Quantity  Discount(%)  \
7         108       Camera  Electronics  30000         8           10
0         101       Laptop  Electronics  70000         5           10
6         107       Tablet  Electronics  25000        15            7

   product number   revenue
7               8  216000.0
0               1  315000.0
6               7  348750.0

In [27]:
# how to add and remove columns
df_1['profit']= df_1['revenue']*0.2
print(df_1)

   Product_ID Product_Name     Category  Price  Quantity  Discount(%)  \
0         101       Laptop  Electronics  70000         5           10
1         102        Mouse  Accessories   1200        50            5
2         103     Keyboard  Accessories   2500        40            5
3         104      Monitor  Electronics  15000        10            8
4         105   Headphones  Accessories   2000        35           10
5         106      Printer  Electronics  10000         7           15
6         107       Tablet  Electronics  25000        15            7
7         108       Camera  Electronics  30000         8           10
8         109   Smartphone  Electronics  40000        12           12
9         110      Speaker  Accessories   3500        25            5

   product number   revenue   profit
0               1  315000.0  63000.0
1               2   57000.0  11400.0
2               3   95000.0  19000.0
3               4  138000.0  27600.0
4               5   63000.0  12600.0
5               6   59500.0  11900.0
6               7  348750.0  69750.0
7               8  216000.0  43200.0
8               9  422400.0  84480.0
9              10   83125.0  16625.0

In [30]:
df_1=df_1.drop(columns=['Price'])
df_1.head(4)

,Product_ID,Product_Name,Category,Quantity,product number,revenue,profit
0,101,Laptop,Electronics,5,1,315000.0,63000.0
1,102,Mouse,Accessories,50,2,57000.0,11400.0
2,103,Keyboard,Accessories,40,3,95000.0,19000.0
3,104,Monitor,Electronics,10,4,138000.0,27600.0

In [32]:
#handling missing data
#isna= is null
print(df_1.isna().sum())

Product_ID        0
Product_Name      0
Category          0
Quantity          0
product number    0
revenue           0
profit            0
dtype: int64

In [36]:
#if present
print(df_1['Quantity'].fillna(df_1['Quantity'].mean()))

0     5
1    50
2    40
3    10
4    35
5     7
6    15
7     8
8    12
9    25
Name: Quantity, dtype: int64

In [38]:
import pandas as pd
data = {
    'Product_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Product_Name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones', 'Printer', 'Tablet', 'Camera', 'Smartphone', 'Speaker'],
    'Category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 'Accessories', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Accessories'],
    'Price': [70000, 1200, 2500, 15000, 2000, 10000, 25000, 30000, 40000,None],
    'Quantity': [5, 50, 40, 10, 35, 7, 15, 8, 12, 25],
    'Discount(%)': [10, 5, 5, 8, 10, 15, 7, 10, 12, 5]
}
df_2=pd.DataFrame(data)
print(df_2)

   Product_ID Product_Name     Category    Price  Quantity  Discount(%)
0         101       Laptop  Electronics  70000.0         5           10
1         102        Mouse  Accessories   1200.0        50            5
2         103     Keyboard  Accessories   2500.0        40            5
3         104      Monitor  Electronics  15000.0        10            8
4         105   Headphones  Accessories   2000.0        35           10
5         106      Printer  Electronics  10000.0         7           15
6         107       Tablet  Electronics  25000.0        15            7
7         108       Camera  Electronics  30000.0         8           10
8         109   Smartphone  Electronics  40000.0        12           12
9         110      Speaker  Accessories      NaN        25            5

In [40]:
df_2['Price']=df_2['Price'].fillna(df_2['Price'].mean())
print(df_2)

   Product_ID Product_Name     Category         Price  Quantity  Discount(%)
0         101       Laptop  Electronics  70000.000000         5           10
1         102        Mouse  Accessories   1200.000000        50            5
2         103     Keyboard  Accessories   2500.000000        40            5
3         104      Monitor  Electronics  15000.000000        10            8
4         105   Headphones  Accessories   2000.000000        35           10
5         106      Printer  Electronics  10000.000000         7           15
6         107       Tablet  Electronics  25000.000000        15            7
7         108       Camera  Electronics  30000.000000         8           10
8         109   Smartphone  Electronics  40000.000000        12           12
9         110      Speaker  Accessories  21744.444444        25            5

In [42]:
# duplicate elements

df_1.duplicated().sum()

np.int64(0)

In [44]:
# grouping and aggregation
type_product= df_1.groupby('Category')['revenue'].sum()
print(type_product)

Category
Accessories     298125.0
Electronics    1499650.0
Name: revenue, dtype: float64

In [46]:
# concatenation and merging
df_3=pd.DataFrame({
    "Category":["Accessories","Electronics"],
    "avg_discount":[10,6]
})
print(df_3)

      Category  avg_discount
0  Accessories            10
1  Electronics             6

In [48]:
joining=pd.merge(df_1,df_3,on='Category',how='left')
joining.head()

,Product_ID,Product_Name,Category,Quantity,product number,revenue,profit,avg_discount
0,101,Laptop,Electronics,5,1,315000.0,63000.0,6
1,102,Mouse,Accessories,50,2,57000.0,11400.0,10
2,103,Keyboard,Accessories,40,3,95000.0,19000.0,10
3,104,Monitor,Electronics,10,4,138000.0,27600.0,6
4,105,Headphones,Accessories,35,5,63000.0,12600.0,10